### ISSUE TITLE
Games freezes when attacking an enemy (skeleton) 

### ISSUE THREAD

**Issue by clairetill** [norestlabs/BrowserQuest#20]
Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
OS: Windows 8.1 64-bit
Address: 0x843B9583375518FbE91A997080615F14b6b753E2

1. Log 1 player into the game
2. Run up until you reach the skeleton opponents
3. Attack one skeleton 

Result: Games freezes 

![1213](https://user-images.githubusercontent.com/4452060/51164410-ae779180-1851-11e9-80f8-7cedd636d5ea.JPG)

**Comment by clairetill** [comment]
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at Object.DrawSprite (http://54.227.190.63:27000/scripts/game/bundle.js:5035:41)
    at SpriteRenderSystem.drawEntity (http://54.227.190.63:27000/scripts/game/bundle.js:11712:26)
    at http://54.227.190.63:27000/scripts/game/bundle.js:11634:22
    at http://54.227.190.63:27000/scripts/game/bundle.js:11660:32
    at Area.forEachPosition (http://54.227.190.63:27000/scripts/game/bundle.js:14249:21)
    at SpriteRenderSystem.forEachVisibleEntityByDepth (http://54.227.190.63:27000/scripts/game/bundle.js:11653:23)
    at SpriteRenderSystem.update (http://54.227.190.63:27000/scripts/game/bundle.js:11633:18)
    at WorldSystem.update (http://54.227.190.63:27000/scripts/game/bundle.js:12479:80)
    at Update (http://54.227.190.63:27000/scripts/game/bundle.js:3156:17)

**Comment by oleg-baturov** [comment]
Verified by e179a4246b391ba24ab686d4e0271309c9d73009
